// Code generated by anygo-encrypt-zip DO NOT EDIT.

package webr

import (
	_ "embed"
	"io/fs"

	"github.com/xanygo/anygo/ds/xzip"
	"github.com/xanygo/anygo/xcodec"
)

var uiAsset fs.FS

//go:embed ui.ez
var _f6d9e96ae3e47c0e08cbfcb1a1e81088 []byte

func init() {
	dz := &xcodec.AesOFB{
		Key: string([]byte{
			'0', '8', 'c', 'c', '6', '3', 'c', '2',
			'4', 'f', '7', '7', 'f', 'c', '1', 'd',
			'4', '1', '4', '1', '6', '6', '3', 'f',
			'c', 'b', '9', 'a', '9', 'd', '2', '6',
		}),
	}
	uiAsset = xzip.MustDecrypt(_f6d9e96ae3e47c0e08cbfcb1a1e81088, dz)
	clear(_f6d9e96ae3e47c0e08cbfcb1a1e81088)
	_f6d9e96ae3e47c0e08cbfcb1a1e81088 = nil
}
