// Code generated by anygo-encrypt-zip DO NOT EDIT.

package webr

import (
	_ "embed"
	"io/fs"

	"github.com/xanygo/anygo/ds/xsync"
	"github.com/xanygo/anygo/ds/xzip"
	"github.com/xanygo/anygo/xcodec"
)

//go:embed ui.ez
var _050d0826f4cff86d182238b2796315ba []byte

var _050d0826f4cff86d182238b2796315baOnce = &xsync.OnceInit[fs.FS]{
	New: func() fs.FS {
		dz := &xcodec.AesOFB{
			Key: string([]byte{
				'0', '8', 'c', 'c', '6', '3', 'c', '2',
				'4', 'f', '7', '7', 'f', 'c', '1', 'd',
				'4', '1', '4', '1', '6', '6', '3', 'f',
				'c', 'b', '9', 'a', '9', 'd', '2', '6',
			}),
		}
		rd := xzip.MustDecrypt(_050d0826f4cff86d182238b2796315ba, dz)
		clear(_050d0826f4cff86d182238b2796315ba)
		_050d0826f4cff86d182238b2796315ba = nil
		return rd
	},
}

func UI() fs.FS {
	return _050d0826f4cff86d182238b2796315baOnce.Load()
}
